### PR TITLE
aparently /scratch/local/user is not accessible except the job folder

### PR DESCRIPTION
**Pull request by vmiheer**

### CODE REVIEW

**Review by mcuma — COMMENTED** [review]
/scratch/local depends on what machine one is on.

On the compute nodes, the $SLURM_JOB_ID is needed, but, on interactive nodes it's not. 

Since we mostly build on interactive nodes, the current directory is valid. If the /scratch/local is not available on the node then the next dir in line is used, thus I suggest not to replace but append the dir with $SLURM_JOB_ID.

**Comment by vmiheer** [comment]
I think building on the interactive node would get emails sent to me for violating policy :).

**Comment by mcuma** [comment]
Possibly but not necessarily as Arbiter whitelists the compilers.

**Comment by vmiheer** [comment]
Okay either rustc is not considered compiler by arbiter or head node doesn't support compilation without violation :).

**Comment by mcuma** [comment]
Answered original question, and rustc is not as widely used yet to warrant Arbiter whitelisting for now.

**Pull request closed without merging**
